#ifndef DRV_EEP_INC_H
#define DRV_EEP_INC_H

#define	EEP_READY_FAIL		1
#define	EEPROM_IS_READY		((NVMCTRL.STATUS >> NVMCTRL_EEBUSY_bp) & 0x01)

#define	INT_EEP_ENABLE			(NVMCTRL.INTCTRL = NVMCTRL.INTCTRL | (1<<NVMCTRL_EEREADY_bp))
#define	INT_EEP_DISABLE			(NVMCTRL.INTCTRL = NVMCTRL.INTCTRL & (0<<NVMCTRL_EEREADY_bp))

typedef enum{
	EEP_STATE_BOOT,
	EEP_STATE_READY,
	EEP_STATE_READ,
	EEP_STATE_WRITE
}EEP_STATE;

#endif
