
enum{
	PALSE_SPEED,
	PALSE_REV,
	EEP_SUM,
	EEP_DATA_MAX
};

#define	PALSE_SPEED_MIN	1
#define	PALSE_SPEED_MAX	5
#define	PALSE_SPEED_DEFAULT	1
#define PALSE_REV_MIN	1
#define PALSE_REV_MAX	9
#define PALSE_REV_DEFAULT	4