#ifndef LNK_IN_EEP_INC_H
#define LNK_IN_EEP_INC_H

enum{
	PALSE_SPEED,
	PALSE_REV,
	EEP_SUM,
	EEP_DATA_MAX
};

#define	PALSE_SPEED_MIN	0
#define	PALSE_SPEED_MAX	5
#define	PALSE_SPEED_DEFAULT	1
#define PALSE_REV_MIN	0
#define PALSE_REV_MAX	8
#define PALSE_REV_DEFAULT	4

#endif